name: Java Maven
'on':
  push:
    branches:
      - master
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: temurin
          cache: maven
#      - name: Install Toolchain JDK
#        uses: battila7/jdk-via-jabba@v1
#        with:
#          jdk: openjdk-ri@1.17.0
#          javaHomeEnvironmentVariable: JDK_17
#      - name: Set up Toolchain
#        shell: bash
#        run: |
#          mkdir -p $HOME/.m2 \
#          && cat << EOF > $HOME/.m2/toolchains.xml
#          <?xml version="1.0" encoding="UTF8"?>
#          <toolchains>
#            <toolchain>
#              <type>jdk</type>
#                <provides>
#                  <version>17</version>
#                  <vendor>adopt</vendor>
#                </provides>
#                <configuration>
#                  <jdkHome>${{ env.JDK_17 }}</jdkHome>
#                </configuration>
#            </toolchain>
#          </toolchains>
#          EOF
      - name: Build with Maven
        run: mvn -B install --file pom.xml -Popensource
#      - name: Update dependency graph
#        uses: >-
#          advanced-security/maven-dependency-submission-action@571e99aab1055c2e71a1e2309b9691de18d6b7d6

      - name: Deploy package
        env:
          REPOSITORY_URL: ${{ secrets.REPOSITORY_URL }}
          REPOSITORY_USERID: ${{ secrets.REPOSITORY_USERID }}
          REPOSITORY_CREDENTIALS: ${{ secrets.REPOSITORY_CREDENTIALS }}
        run: |
          mkdir -p ~/.m2
          echo "<settings><servers><server><id>neverpile</id><username>${REPOSITORY_USERID}</username><password>${REPOSITORY_CREDENTIALS}</password></server></servers></settings>" > ~/.m2/settings.xml 
          mvn deploy -Dmaven.test.skip.exec=true -DaltDeploymentRepository=neverpile::default::${REPOSITORY_URL}